config/routes.rb
Rails.application.routes.draw do
  root "sessions#create"

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :show, :destroy]

  get "/home", to: "home#index"

 
  post '/user_friends/unfriend', to: "user_friend#unfriend"
  post '/user_friends/friend', to: "user_friend#friend"
  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :profile
  has_many :user_friends
  has_many :posts

  accepts_nested_attributes_for :profile, update_only: true
  accepts_nested_attributes_for :posts
end

app/models/user_friend.rb
class UserFriend < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :friend, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to home_path
  end

  private
  def comment_params
    params.require(:comment).permit(:detail, :post_id).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    Post.create(post_params)
    redirect_to home_path
  end

  private
  def post_params
    params.require(:post).permit(:detail).merge(user:current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to home_path
    else
      message = "something went wrong, make sure your data are correct"
      redirect_to login_path, notice: message
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'logged out succefully'
  end
end

app/controllers/user_friend_controller.rb
class UserFriendController < ApplicationController
  def friend
      UserFriend.create(user_friend_params)
      redirect_to home_path, notice: 'friend added succefully'
  end

  def unfriend
      UserFriend.where(user_friend_params)
      .or(UserFriend.where(friend_id:user_friend_params[:user_id], user_id: user_friend_params[:friend_id]))
      .destroy_all
      redirect_to home_path, notice: 'friend removed succefully'
  end

  private
  def user_friend_params
    params.permit(:user_id, :friend_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def update
    User.find(params[:id]).update(user_params)
    redirect_to home_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, profile_attributes: {})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def get_friends
    User.joins(:profile).where.not(id:current_user.id, profiles: {name: nil}).map do |user|
      already_friend = UserFriend.where(user_id:current_user.id, friend_id: user.id)
                        .or(UserFriend.where(friend_id:current_user.id, user_id: user.id))
                        .present?
      {
        id: user.id,
        profile_name: user.profile.name,
        already_friend: already_friend
      }
    end.compact
  end
  def get_posts
     user_ids = UserFriend.where(user_id:current_user.id).map(&:friend_id)
     user_ids << UserFriend.where(friend_id:current_user.id).map(&:user_id)
     user_ids << current_user.id
     Post.where(user_id: user_ids.flatten).order(created_at: :desc)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_friend_helper.rb
module UserFriendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/add.html.erb
<h1>Comments#add</h1>
<p>Find me in app/views/comments/add.html.erb</p>

app/views/home/_feed.html.erb
<div class="card">
  <h3>Create post</h3>
  <%= form_for Post.new do |f| %>
    <%= f.text_area :detail, placeholder: "what are you thinking?" %>
    <%= f.submit "create comment"%>
  <% end %>
</div>
<% get_posts.each do |post| %>
  <div class="card">
    <h4> <%= post.user.profile.name %> </h4>
    <p class="date"> <%= post.created_at.strftime("%B %d at %H:%M") %></p>
    <div >
      <div >
        <h5>Comments</h5>
        <% post.comments.order(created_at: :desc).each do |comment| %>
          <div class="card">
            <h4> <%= comment.user.profile.name %> </h4>
            <p class="date"> <%= comment.created_at.strftime("%B %d at %H:%M") %></p>
            <h6> <%= comment.detail %></h6>
          </div>
        <% end %>
      </div>
      <%= form_for Comment.new do |f| %>
        <%= f.hidden_field :post_id, :value => post.id %>
        <%= f.text_area :detail, placeholder: "comment" %>
        <%= f.submit "insert comment"%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/home/_friends.html.erb
<% get_friends.each do |val| %>
  <%= val[:profile_name] %>
  <%= link_to('add friend', user_friends_friend_path(user_id: current_user.id, friend_id: val[:id]), method: :post) if !val[:already_friend] %>
  <%= link_to('remove friend', user_friends_unfriend_path(user_id: current_user.id, friend_id: val[:id]), method: :post ) if val[:already_friend] %>
  <br>
<% end %>

app/views/home/_profile.html.erb
  <%= form_for current_user do |f| %>
  <%= f.fields_for :profile, current_user.profile || Profile.new do |profile_form| %>
    <%= profile_form.label :name %>
    <%= profile_form.text_field :name, placeholder: "Your full name here" %>
    <%= profile_form.label :bio %>
    <%= profile_form.text_area :bio, placeholder: "tell me about you" %>
  <% end %>
  <%= f.submit "Update Bio"%>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <div class="card">
    <h3>Bio</h3>
    <%= render 'profile' %>
  </div>
  <% if current_user.profile %>
    <div class="card">
      <h3>friends</h3>
      <%= render 'friends' %>
    </div>
    <%= render 'feed' %>
  <% else %>
    <div class="card" style="color:red;">
      you need to capture your bio to see friends and start your posts
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <h4 class="brand-logo big-logo">Social Test</h4>
      <ul class="right">
        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/add.html.erb
<h1>Posts#add</h1>
<p>Find me in app/views/posts/add.html.erb</p>

app/views/user_friend/add.html.erb
<h1>UserFriend#add</h1>
<p>Find me in app/views/user_friend/add.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="card">
    <h2>Create Account</h2>
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Create Account"%>
    <% end %>
  </div>
</div>